version: "3.8"
services:
  postgres:
    container_name: postgres
    restart: always
    image: postgres
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST_AUTH_METHOD=md5
    volumes:
      - pgdata:/var/lib/postgresql/data:rw
    expose:
      - 5432
    networks:
      - microservices

  auth:
    container_name: auth
    build:
      context: .
      dockerfile: Dockerfile
    image: auth:latest
    environment:
      USER_SVC_ADDRESS: "user:9998"
    volumes:
      - .:/service
    networks:
      - microservices
    depends_on:
      - postgres
    restart: always

networks:
  microservices:
    external: true

volumes:
  pgdata:
    external: true
    name: authdata