version: "3.8"
services:
  auth:
    container_name: auth
    build:
      context: .
      dockerfile: Dockerfile
    image: auth:latest
    environment:
      USER_HOST: user
    volumes:
      - .:/service
    networks:
      - gateway_microservices
    restart: always

networks:
  gateway_microservices:
    external: true