version: "3.8"
services:
  auth:
    container_name: auth
    build:
      context: .
      dockerfile: Dockerfile
    image: auth:latest
    environment:
      USER_SVC_ADDRESS: "user:9998"
    volumes:
      - .:/service
    networks:
      - microservices
    restart: always

networks:
  microservices:
    external: true