"""set avatart user id unique

Revision ID: 87e7f51e7d90
Revises: d88219a92800
Create Date: 2022-12-20 11:29:58.650587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87e7f51e7d90'
down_revision = 'd88219a92800'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'user_avatar', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_avatar', type_='unique')
    # ### end Alembic commands ###
